config/routes.rb
Rails.application.routes.draw do
  resources :artists do
    resources :songs
  end

  resources :songs
  resources :playlists
  get '/auth/spotify/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  validates :image_path, presence: true
  has_many :songs
end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  has_many :playlist_songs
  has_many :songs, through: :playlist_songs
end

app/models/playlist_song.rb
class PlaylistSong < ActiveRecord::Base
  belongs_to :song
  belongs_to :playlist
end

app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :artist
end

app/models/user.rb
class User < ActiveRecord::Base
  def self.find_or_create_from_auth(auth)
    User.find_or_create_by(
    provide: auth["provider"],
    uid: auth["info"]["id"],
    name: auth["info"]["display_name"]
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  def index
    @artists = Artist.all
  end

  def new
    @artist = Artist.new
  end

  def create
    @artist = Artist.new(artist_params)
    if @artist.save
      redirect_to @artist
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @artist.update(artist_params)
      redirect_to @artist
    else
      render :edit
    end
  end

  def destroy
    @artist.destroy
    redirect_to artists_path
  end

private

  def set_artist
    @artist = Artist.find(params[:id])
  end

  def artist_params
    params.require(:artist).permit(:name, :image_path, :discography)
  end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  def new
    @playlist = Playlist.new
  end

  def create
    @playlist = Playlist.create(playlist_params)
    redirect_to @playlist
  end

  def index
    @playlists = Playlist.all
  end

  def show
    @playlist = Playlist.find(params[:id])
  end

  def edit
    @playlist = Playlist.find(params[:id])
  end

  def update
    @playlist = Playlist.find(params[:id])
    if @playlist.update(playlist_params)
      redirect_to @playlist
    else
      render :edit
    end
  end

  def destroy
    playlist = Playlist.find(params[:id])
    playlist.destroy
    redirect_to playlists_path
  end

  private

  def playlist_params
    params.require(:playlist).permit(:name, song_ids: [])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.find_or_create_from_auth(request.env['omniauth.auth'])
    if @user
      session[:user_id] = @user.id
      redirect_to playlists_path
    end
  end

  def destroy
    session.clear
    redirect_to playlists_path
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def index
    @songs = Song.all
  end

  def new
    @artist = Artist.find(params[:artist_id]) #we need to find the artist
    @song = @artist.songs.new #create the song
  end

  def create
    @artist = Artist.find(params[:artist_id]) #error here
    @song = @artist.songs.create(song_params)
    redirect_to song_path(@song)
  end

  def update
    @song = Song.find(params[:id])
    @song.update(song_params)
    redirect_to @song
  end

  def edit
    #params = {"controller"=>"songs", "action"=>"edit", "id"=>"179"}
    @song = Song.find(params[:id]) #error here
    # @song = @song.artist #worked with rick on this one
  end

  def show
    @song = Song.find(params[:id])
    @artist = @song.artist
  end

  def destroy
    song = Song.find(params[:id])
    song.destroy
    redirect_to songs_path
  end

  private
  def song_params
    params.require(:song).permit(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/views/artists/_form.html.erb
<%= form_for(@artist) do |f| %>
<%= render partial: "shared/error" %>
    <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :image_path %>
  <%= f.text_field :image_path %>

  <%= f.label :discography %>
  <%= f.text_field :discography %>
  <%= f.submit%>
<% end %>

app/views/artists/edit.html.erb
<h1> Edit the Artist</h1>

<%= render partial: "form" %>

app/views/artists/index.html.erb
<%= stylesheet_link_tag "application.css" %>
<h1>All Artists</h1>
<p><%= link_to "New artist", new_artist_path %></p>
<table border = "1">
  <% @artists.map do |artist| %>
  <tr>
  <td><%= link_to artist.name, artist_path(artist)%></td>
<td><%= image_tag artist.image_path %></td>
<td><%= image_tag artist.discography %></td>
</tr>
<% end  %>
</table>
<p><%= link_to "All Songs", songs_path %></p>
<p><%= link_to "All Playlists", playlists_path %></p>

app/views/artists/new.html.erb
<%= form_for(@artist) do |f| %>
  <% if @artist.errors.any? %>
    <h2><%= pluralize(@artist.errors.count, "error") %> prohibited this record from being saved:</h2>
    <ul>
      <% @artist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :image_path %>
  <%= f.text_field :image_path %>

  <%= f.label :discography %>
  <%= f.text_field :discography %>

  <%= f.submit %>
<% end %>

app/views/artists/show.html.erb
<h1><%= @artist.name %> </h1>
<%= image_tag @artist.image_path %>
<p><%= link_to "Edit Artist", edit_artist_path(@artist) %></p>
<p><%= link_to "Delete Artist", artist_path(@artist), method: :delete, data: {confirm: "Really delete the artist?"} %></p>
<p><%= link_to "New Song", new_artist_song_path(@artist) %></p>
<p><%= link_to "All Artists", artists_path %></p>
<p><%= link_to "All Playlists", playlists_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MixMaster</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if current_user  %>
<h3>Welcome, <%= current_user.name %></h3>
<%= link_to "Sign out", logout_path, method: :delete %>
<% else %>
<%= link_to "Sing in with Spotify", "/auth/spotify" %>
<% end %>
<%= yield %>

</body>
</html>

app/views/playlists/_form.html.erb
<% Song.all.map do |song| -%>
<div>
  <%= check_box_tag(:song_ids, song.id, @playlist.songs.include?(song), :name => 'playlist[song_ids][]', id: "song-#{song.id}") %>
  <%= song.title %>
</div>
<%end %>
<%= f.submit %>

app/views/playlists/edit.html.erb
<h1> Edit the Playlist</h1>
<%= form_for(@playlist) do |f| %>

<%= f.label :playlist_name %>
<%= f.text_field :name %>

<%= render partial: "form", locals: {f: f}  %>
<% end %>

app/views/playlists/index.html.erb
<h1>All Playlists</h1>
  <ul>
<% @playlists.map do |f| %>
<li><%= link_to f.name, playlist_path(f)%></li>
<% end %>
</ul>

<p><%= link_to "New Playlist", new_playlist_path %><p>
<p><%= link_to "All Artists", artists_path %><p>
<p><%= link_to "All Songs", songs_path %><p>

app/views/playlists/new.html.erb
<h1>New Playlist</h1>
<%= form_for(@playlist) do |f| %>
  <% if @playlist.errors.any? %>
    <h2><%= pluralize(@playlist.errors.count, "error") %> prohibited this record from being saved:</h2>
    <ul>
      <% @playlist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

<%= f.text_field :name %>

<%= render partial: "form", locals: {f: f} %>
<%end %>

app/views/playlists/show.html.erb
<h1><%= @playlist.name %> </h1>
<ul>
  <% @playlist.songs.each do |song| %>
  <li><%=  link_to song.title, song%></li>
  <% end %>
</ul>
<p><%= link_to "Edit Playlist", edit_playlist_path(@playlist) %></p>
<p><%= link_to "Delete Playlist", playlist_path(@playlist), method: :delete, data: {confirm: "Really delete playlist?"} %></p>
<p><%= link_to "All Playlists", playlists_path %></p>

app/views/shared/_error.html.erb
  <% if @artist.errors.any? %>
    <h2><%= pluralize(@artist.errors.count, "error") %> prohibited this record from being saved:</h2>
    <ul>
      <% @artist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
  

app/views/songs/_form.html.erb
<%= form_for(target) do |f| %>
<%= f.label :title %>
<%= f.text_field :title %>
<%= f.submit %>
<% end %>

app/views/songs/edit.html.erb
<h1> Edit the Song</h1>
<%= render partial: "form", locals: { target: @song} %>

app/views/songs/index.html.erb
<h1>All Songs</h1>
<ul>
  <% @songs.map do |song| %>
  <li><%= link_to song.title, song_path(song)%></li>
<% end  %>
</ul>
<p><%= link_to "All Artists", artists_path %></p>
<p><%= link_to "All Playlists", playlists_path %></p>

app/views/songs/new.html.erb
<h1>New Song</h1>
<p>Add a new song for <%= @artist.name %></p>
<%= form_for([@artist, @song]) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.submit %>
<% end %>

app/views/songs/show.html.erb
<h1><%= @song.title %> </h1>
<p><%= link_to "Edit Song", edit_song_path(@song) %></p>
<p><%= link_to "Delete Song", song_path(@song), method: :delete, data: {confirm: "Really delete the song?"} %></p>
  <p><%= link_to @artist.name, artist_path(@artist)%></p>
  <p><%= link_to "All Songs", songs_path%></p>